// Sugestões de cargos populares no mercado brasileiro
export const JOB_ROLE_SUGGESTIONS = [
  // Tecnologia
  "Desenvolvedor Frontend",
  "Desenvolvedor Backend",
  "Desenvolvedor Full Stack",
  "Engenheiro de Software",
  "Analista de Sistemas",
  "Arquiteto de Software",
  "DevOps Engineer",
  "Engenheiro de Dados",
  "Cientista de Dados",
  "Analista de Dados",
  "Product Manager",
  "Scrum Master",
  "Agile Coach",
  "UX Designer",
  "UI Designer",
  "Designer de Produto",
  "QA Engineer",
  "Analista de Qualidade",
  "Engenheiro de Machine Learning",
  "Administrador de Sistemas",
  "Analista de Segurança da Informação",
  "Tech Lead",
  "CTO - Chief Technology Officer",
  
  // Marketing e Vendas
  "Analista de Marketing",
  "Gerente de Marketing",
  "Coordenador de Marketing Digital",
  "Social Media Manager",
  "Analista de SEO",
  "Especialista em Growth",
  "Executivo de Vendas",
  "Gerente Comercial",
  "Account Manager",
  "Business Development Representative (BDR)",
  "Sales Development Representative (SDR)",
  "Customer Success Manager",
  
  // Recursos Humanos
  "Analista de Recursos Humanos",
  "Business Partner de RH",
  "Recrutador",
  "Tech Recruiter",
  "Coordenador de Recrutamento e Seleção",
  "Analista de Departamento Pessoal",
  "Gerente de RH",
  
  // Finanças
  "Analista Financeiro",
  "Controller",
  "Gerente Financeiro",
  "Analista de Controladoria",
  "Analista Contábil",
  "CFO - Chief Financial Officer",
  
  // Administrativo
  "Assistente Administrativo",
  "Analista Administrativo",
  "Coordenador Administrativo",
  "Gerente de Operações",
  "Assistente Executivo",
  
  // Outros
  "Advogado",
  "Consultor Jurídico",
  "Engenheiro Civil",
  "Arquiteto",
  "Designer Gráfico",
  "Redator",
  "Jornalista",
  "Psicólogo Organizacional",
];

// Sugestões de empresas conhecidas no Brasil
export const COMPANY_SUGGESTIONS = [
  // Big Techs
  "Google",
  "Meta (Facebook)",
  "Amazon",
  "Microsoft",
  "Apple",
  "Netflix",
  "Uber",
  "Airbnb",
  "LinkedIn",
  "Twitter (X)",
  
  // Empresas Brasileiras de Tecnologia
  "Nubank",
  "Mercado Livre",
  "iFood",
  "Stone",
  "PagSeguro",
  "Loggi",
  "99",
  "Movile",
  "Wildlife Studios",
  "VTEX",
  "Totvs",
  "Locaweb",
  "Resultados Digitais (RD Station)",
  "Conta Azul",
  "Pipefy",
  "QuintoAndar",
  "Loft",
  "Creditas",
  "Gympass (Wellhub)",
  "Magazine Luiza",
  
  // Bancos e Fintechs
  "Banco do Brasil",
  "Bradesco",
  "Itaú Unibanco",
  "Santander",
  "Caixa Econômica Federal",
  "BTG Pactual",
  "Inter",
  "C6 Bank",
  "Neon",
  "PicPay",
  
  // Varejo
  "Via Varejo",
  "Americanas",
  "Casas Bahia",
  "Ponto Frio",
  "Grupo Carrefour",
  "Grupo Pão de Açúcar",
  "Raia Drogasil",
  
  // Indústria
  "Ambev",
  "Petrobras",
  "Vale",
  "Embraer",
  "Gerdau",
  "Natura &Co",
  
  // Consultorias
  "McKinsey & Company",
  "Boston Consulting Group (BCG)",
  "Bain & Company",
  "Deloitte",
  "PwC",
  "EY",
  "KPMG",
  "Accenture",
];
