project_id = "wmwpjbagtohitynxoqqx"

[functions.parse-resume]
verify_jwt = false

[functions.parse-resume-health]
verify_jwt = false

[functions.parse-resume-test]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.lookup-cep]
verify_jwt = false
