// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmwpjbagtohitynxoqqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indtd3BqYmFndG9oaXR5bnhvcXF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTg3NTEsImV4cCI6MjA3MzM3NDc1MX0.mD8iOuTzZvbxBWRGqgA7_fhEE5YsZNVOCqmf0uJ8iFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});